### PR TITLE
Add workflow, update dependencies and add spawn module

### PR DESCRIPTION
**Pull request by Elikill58**
Fixed:
- Use latest API, fix error with new plugins

Added :
- Github workflow
- Spawn module with auto-generator

### CODE REVIEW

**Comment by ZakShearman** [comment]
Thanks for the contribution.

I'm just gonna fix some styling issues with this. In the future I'll provide some styling guidance so people actually know what I'd prefer.

**Comment by ZakShearman** [comment]
Also not going to allow it to be switched to SNAPSHOT as it's known that sometimes SNAPSHOT just doesn't work with JitPack. Many people have experienced this when using Minestom and other projects.

**Comment by ZakShearman** [comment]
lmk if you're happy with the changes that I've made just to make sure it hasn't removed any of your work and then I'm happy merging this.

I've left this project for a while and I'm probably going to look into improving some things here soon (maybe removing OPs, IMO should be separated into an extension and just use luckperms).

**Comment by Elikill58** [comment]
Hi,
I'm happy that you look this quickly, and review it. So, thanks you for this.

Also, I suggest you to keep OP command until there isn't official release of Luckperms in Minestom

**Pull request merged**
